name: share_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.0.0
  expandable_text: ^2.3.0
  event_bus: ^2.0.0
  flutter_custom_clippers: ^2.0.0
  intl: ^0.17.0
  font_awesome_flutter: ^10.2.1
  dio: ^4.0.6
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

#  assets:
#    - images/a_dot_burr.jpeg
#    - images/a_dot_ham.jpeg
